---
title: "SDS 192 Assignment"
subtitle: "SDS 192"
author: "Malaika Kironde, Jack Kendrick, Lika Mikhelashvili"
date: "`r format(Sys.Date(), '%B %e, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  echo = TRUE
)
library(tidyverse)
library(sds192)
library(fivethirtyeight)
library(ggthemes)
```

## Section 1

```{r}
# Adding in column for Region to dataset
state_region <- data.frame(state = state.abb, region = state.region)
state_region <- rbind(state_region, data.frame(state = "DC", region = "South"))

police_data <- merge(police_killings, state_region, by = "state")
```


x-axis: `h_income`

y-axis: number of people falling into each bin of household income

color coded to races 

```{r graph1, message=FALSE}
#Plot Code - Wrapping by Race
ggplot(data=police_data, aes(h_income)) +
  geom_histogram() +
  theme_fivethirtyeight()+
  theme(axis.title = element_text())+
  scale_fill_fivethirtyeight()+
  facet_wrap(~raceethnicity) + 
  scale_x_continuous(name = "Tract-level Median Household Income")+
  scale_y_continuous(name = "Number of Individuals Killed")+
  labs(
    title = "Median Household Income Distribution Among People Killed by the Police", 
    subtitle = "By race",
    caption = "Source: fivethirtyeight"
  )
```

```{r racial_breakdown, message=FALSE}
ggplot(data = police_killings, aes(state))+
  coord_flip()+
  geom_bar(aes(x = state, fill = raceethnicity))+
    labs(
    title = "Racial Breakdown of People Killed by the Police", 
    caption = "Source: fivethirtyeight"
  )
```



## Word count

```{r word_count, message=FALSE, echo=FALSE}
text_stats()
```

## Standards

In this assignment, we attempted the following [standards](https://beanumber.github.io/sds192/standards.html):

- `r standard_button("markdown")`: We met the Markdown standard because we...
- `r standard_button("aesthetics")`: We met the Aesthetics standard because we...


